json.user_id      @delete_user_video.user_id 
json.technique_id     @delete_user_video.technique_id 
json.video_id     @delete_user_video.video_id 
json.name     @delete_user_video.name 
json.size       @delete_user_video.size  
json.ssl_url      @delete_user_video.ssl_url  
json.thumb_name     @delete_user_video.thumb_name
json.thumb_size     @delete_user_video.thumb_size
json.thumb_ssl_url    @delete_user_video.thumb_ssl_url
